export const GET_PROFILE = 'GET_PROFILE';

export const GET_DATABASE = 'GET_DATABASE';

export const GET_GEN = 'GET_GEN';

export const SAVE_DELPIC = 'SAVE_DELPIC';

export const ADD_CAROUSEL = 'ADD_CAROUSEL';
export const DELETE_CAROUSEL = 'DELETE_CAROUSEL';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const MODIFY_CATEGORY = 'MODIFY_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
